### ISSUE TITLE
query

### ISSUE THREAD

**Issue by anu-oss** [debamitr1012/TrafficSignRecognition_PyTorch#1]
Hi there.
May I know if you're accepting contribution in documentation as well?

**Comment by debamitr1012** [comment]
Yes please text me at +91 9836578565Sent from Android deviceOn Feb 25, 2022 12:17 AM, anu-oss ***@***.***> wrote:
Hi there.
May I know if you're accepting contribution in documentation as well?

**Comment by debamitr1012** [comment]
WhatsApp me at +91 9836578565
