### ISSUE TITLE
Transfer learning model to predict the traffic signs. #GSSOC'22

### ISSUE THREAD

**Issue by hemhemoh** [debamitr1012/TrafficSignRecognition_PyTorch#11]
Somebody has previously been assigned the issue of using deep learning to predict the traffic sign but I'd love to also use transfer learning to predict the traffic signs.

**Comment by debamitr1012** [comment]
sure feel free to contribute

**Comment by hemhemoh** [comment]
Okay, is there a need for me to wait for you to assign the issue to me?

**Comment by debamitr1012** [comment]
no no its ok you can carry on... if needed whatsapp me at +91 9836578565

**Comment by Rasikamurali** [comment]
Hello, I'm a participant in GSSoC '22. Can I also contribute to this?

**Comment by debamitr1012** [comment]
okay

**Comment by hemhemoh** [comment]
> Hello, I'm a participant in GSSoC '22. Can I also contribute to this? 

I'm almost done with it sha. Maybe I should let you know the pretrained models I'm using, so we won't be using the same thing

**Comment by Rasikamurali** [comment]
> > Hello, I'm a participant in GSSoC '22. Can I also contribute to this?
> 
> I'm almost done with it sha. Maybe I should let you know the pretrained models I'm using, so we won't be using the same thing

Yes that would be useful. Thanks

**Comment by hemhemoh** [comment]
> > > Hello, I'm a participant in GSSoC '22. Can I also contribute to this?
> > 
> > 
> > I'm almost done with it sha. Maybe I should let you know the pretrained models I'm using, so we won't be using the same thing
> 
> Yes that would be useful. Thanks

I am using Alexnet, still testing will let you know if i switch to any other architecture

**Comment by debamitr1012** [comment]
> > > > Hello, I'm a participant in GSSoC '22. Can I also contribute to this?
> > > 
> > > 
> > > I'm almost done with it sha. Maybe I should let you know the pretrained models I'm using, so we won't be using the same thing
> > 
> > 
> > Yes that would be useful. Thanks
> 
> I am using Alexnet, still testing will let you know if i switch to any other architecture

okay no problem

**Comment by hemhemoh** [comment]
Hi @debamitr1012 please add level and the #GSSOC'22 tag to it too.

**Comment by debamitr1012** [comment]
> Hi @debamitr1012 please add level and the #GSSOC'22 tag to it too.

Ok sure I will do it by today
