### ISSUE TITLE
Improving the README.md file

### ISSUE THREAD

**Issue by SayanSaha01** [debamitr1012/TrafficSignRecognition_PyTorch#2]
Hello i am a participant in GSSoc 22 can you please assign this issue to me

**Comment by AniruddhA-Omni** [comment]
Hello, I can work on this issue very well. Can you assign this to me?

**Comment by debamitr1012** [comment]
WhatsApp me at +91 9836578565

**Comment by akashroy1** [comment]
Hello! Can anyone please brief me about the issue?

**Comment by coolblizzarts** [comment]
Hello Payal here, I would like to contribute to this issue. Can you please assign it to me. Regards.
