### ISSUE TITLE
Traffic Sign Recognition

### ISSUE THREAD

**Issue by gitarshmah** [debamitr1012/TrafficSignRecognition_PyTorch#3]

**Comment by AniruddhA-Omni** [comment]
I can do this part.

**Comment by Suvodeep-Das** [comment]
I can work on this.

**Comment by debamitr1012** [comment]
WhatsApp me at +91 9836578565

**Comment by gitarshmah** [comment]
I can work on this project

**Comment by debamitr1012** [comment]
WhatsApp me at +91 9836578565.
    On Tuesday, 1 March, 2022, 07:44:11 pm IST, Arshmah Saeed ***@***.***> wrote:  
 
 


I can work on this project
