### ISSUE TITLE
Deep Learning Model to Predict The Traffic Sign

### ISSUE THREAD

**Issue by srajan-kiyotaka** [debamitr1012/TrafficSignRecognition_PyTorch#4]
Deep Learning CNN Model to recognize the traffic sign.

**Comment by srajan-kiyotaka** [comment]
Hii!
I am a participant in GSSOC'22. Please assign me this issue.

**Comment by SayanSaha01** [comment]
Hey i am a participant is GSSOC'22. I will create a Deep Learning Model with 97% + accuracy. Please assign this issue to me

**Comment by debamitr1012** [comment]
WhatsApp me at +91 9836578565
