### ISSUE TITLE
Want to add CONTRIBUTE.md file

### ISSUE THREAD

**Issue by rimsha-salahuddin** [debamitr1012/TrafficSignRecognition_PyTorch#6]
So the all the new contributors can know the code of conduct and how to contribute to this repository

**Comment by debamitr1012** [comment]
Yes you can do it. Create pull request issues then you can easily do it. If you want to know something more WhatsApp me at 
+91 9836578565.

**Comment by rimsha-salahuddin** [comment]
please assign this issue to me so that i can start working on it

**Comment by Priyanka-Chettri** [comment]
Hey, I am Priyanka i want to work on this issue, please consider me next on the queue

**Comment by ritikaaaa177** [comment]
@debamitr1012 Hello sir, I am a GSSOC '23 participant and i would like to work on this documentation. Please assign me this issue.
